# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-17 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190417_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'doctor'), (2, 'nurse'), (3, 'costumer')], null=True),
        ),
    ]
