# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190417_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='worker',
            name='user_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'doctor'), (2, 'nurse')], null=True),
        ),
    ]
