# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190418_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='user_type',
        ),
    ]
