# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190418_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_worker',
        ),
        migrations.AddField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='student status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_nurse',
            field=models.BooleanField(default=False, verbose_name='student status'),
        ),
    ]
