# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-18 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190418_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_costumer',
            field=models.BooleanField(default=False, verbose_name='costumer status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_doctor',
            field=models.BooleanField(default=False, verbose_name='doctor status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_nurse',
            field=models.BooleanField(default=False, verbose_name='nurse status'),
        ),
    ]
