# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190418_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
