# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-24 03:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_auto_20190419_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emchilgee',
            name='costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
