# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-24 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190419_0256'),
        ('drug', '0003_auto_20190424_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Worker'),
        ),
        migrations.AddField(
            model_name='onosh',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Worker'),
        ),
        migrations.AlterField(
            model_name='history',
            name='costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Costumer'),
        ),
        migrations.AlterField(
            model_name='onosh',
            name='costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Costumer'),
        ),
    ]
