# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-24 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_degree_date'),
        ('drug', '0004_auto_20190424_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug_important',
            name='category',
        ),
        migrations.RemoveField(
            model_name='drug_order',
            name='about',
        ),
        migrations.RemoveField(
            model_name='drug_order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='onosh',
            name='costumer',
        ),
        migrations.RemoveField(
            model_name='onosh',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='onosh',
            name='name',
        ),
        migrations.AddField(
            model_name='drug_important',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='order_status'),
        ),
        migrations.AddField(
            model_name='drug_order',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Worker'),
        ),
        migrations.AddField(
            model_name='emchilgee',
            name='onosh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Onosh'),
        ),
        migrations.AddField(
            model_name='emchilgee',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Worker'),
        ),
        migrations.AddField(
            model_name='onosh',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onosh',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drug_important',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Drug_detail'),
        ),
        migrations.AlterField(
            model_name='drug_order',
            name='recived_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emchilgee',
            name='costumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Costumer'),
        ),
        migrations.AlterField(
            model_name='onosh',
            name='disc',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
