# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-28 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0005_auto_20190424_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug_important',
            name='is_ordered',
        ),
    ]
