# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-28 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0006_remove_drug_important_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emchilgee',
            name='duration',
        ),
        migrations.AddField(
            model_name='emchilgee',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='emchilgee',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
