# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-30 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0007_auto_20190428_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug_important',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
