# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-01 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0009_auto_20190501_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug_important',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='ordered_status'),
        ),
    ]
