# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-01 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0011_auto_20190501_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='emchilgee',
            name='cos_review',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emchilgee',
            name='doctor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emchilgee',
            name='doctor_review',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
