# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-01 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0013_auto_20190501_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emchilgee',
            name='cos_review',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='emchilgee',
            name='doctor_review',
            field=models.IntegerField(default=1),
        ),
    ]
