# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-02 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0016_auto_20190501_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='emchilgee',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='costumer_review',
            name='emchilgee',
            field=models.IntegerField(default=0),
        ),
    ]
