# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-03 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0017_auto_20190502_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onoshdahi_emchilgee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('emchilgee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Emchilgee')),
            ],
        ),
        migrations.RemoveField(
            model_name='drug_important',
            name='emchilgee',
        ),
        migrations.AddField(
            model_name='drug_important',
            name='onoshdahi_emchilgee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Onoshdahi_emchilgee'),
        ),
    ]
