# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-06 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0019_auto_20190503_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug_important',
            name='onoshdahi_emchilgee',
        ),
        migrations.AddField(
            model_name='drug_important',
            name='emchilgee_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Emchilgee_list'),
        ),
    ]
