# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-06 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0020_auto_20190506_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onoshdahi_emchilgee',
            name='emchilgee',
        ),
        migrations.RemoveField(
            model_name='onoshdahi_emchilgee',
            name='emchilgee_list',
        ),
        migrations.AddField(
            model_name='drug_important',
            name='emchilgee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drug.Emchilgee'),
        ),
        migrations.DeleteModel(
            name='Onoshdahi_emchilgee',
        ),
    ]
