# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-08 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0022_days_od_emchilgee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Days_od_emchilgee',
            new_name='Days_of_emchilgee',
        ),
    ]
