# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-13 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0023_auto_20190508_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_code', models.CharField(max_length=100)),
                ('drug_name', models.CharField(max_length=300)),
                ('instructions', models.CharField(max_length=300)),
                ('serial_number', models.CharField(max_length=100)),
                ('producted_date', models.DateField(default=django.utils.timezone.now)),
                ('hadgalah_hugatsaa', models.CharField(max_length=100)),
                ('uildver_ner', models.CharField(max_length=100)),
                ('sanuulga', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Helber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hemjee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Savalgaa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storage_condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('additional', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Drug_category',
            new_name='Drug_type',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='age',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='date',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='drug_catedory',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='factory',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='nairlaga',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='other_side',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='price',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='size',
        ),
        migrations.RemoveField(
            model_name='drug_detail',
            name='zaavar',
        ),
        migrations.AddField(
            model_name='drug_detail',
            name='drug_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Drug_type'),
        ),
        migrations.AddField(
            model_name='drug',
            name='helber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Helber'),
        ),
        migrations.AddField(
            model_name='drug',
            name='hemjee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Hemjee'),
        ),
        migrations.AddField(
            model_name='drug',
            name='savalgaa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Savalgaa'),
        ),
        migrations.AddField(
            model_name='drug',
            name='storage_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Storage_condition'),
        ),
    ]
