# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-13 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_degree_date'),
        ('drug', '0024_auto_20190513_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField(default=django.utils.timezone.now)),
                ('irraved_date', models.DateField(blank=True, null=True)),
                ('is_irraved', models.BooleanField(default=False)),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=100)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Drug')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Other_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('hemjee', models.CharField(max_length=50)),
                ('uildver', models.CharField(max_length=200)),
                ('producted_date', models.DateField(default=django.utils.timezone.now)),
                ('hadgalah_hugatsaa', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ordered_staff',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Other_staff'),
        ),
    ]
