# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-13 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_degree_date'),
        ('drug', '0025_auto_20190514_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='costumer',
        ),
        migrations.AddField(
            model_name='order',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Worker'),
        ),
    ]
