# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-14 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0028_remove_order_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(max_length=100)),
                ('last_transaction', models.DateField(default=django.utils.timezone.now)),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drug.Drug')),
            ],
        ),
        migrations.AlterField(
            model_name='ordered_drug',
            name='qty',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordered_staff',
            name='qty',
            field=models.IntegerField(max_length=100),
        ),
    ]
